# تنسيق Rust
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
format_code_in_doc_comments = true
comment_width = 100
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true
format_strings = true
overflow_delimited_expr = true
condense_wildcard_suffixes = true